//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis_SCADA.Model
{
    using System;
    using System.Collections.Generic;
    using Thesis_SCADA.ViewModel;

    public partial class ProcessEvent: BaseViewModel
    {
        public int Id { get; set; }

        private string _EventClass;
        public string EventClass { get => _EventClass; set { _EventClass = value; OnPropertyChanged(); } }

        private Nullable<int> _EventID;
        public Nullable<int> EventID { get => _EventID; set { _EventID = value; OnPropertyChanged(); } }

        private Nullable<int> _SeverityLevel;
        public Nullable<int> SeverityLevel { get => _SeverityLevel; set { _SeverityLevel = value; OnPropertyChanged(); } }

        private string _SourceName;
        public string SourceName { get => _SourceName; set { _SourceName = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _TimeRaised;
        public Nullable<System.DateTime> TimeRaised { get => _TimeRaised; set { _TimeRaised = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _TimeConfirmed;
        public Nullable<System.DateTime> TimeConfirmed { get => _TimeConfirmed; set { _TimeConfirmed = value; OnPropertyChanged(); } }

        private Nullable<System.DateTime> _TimeCleared;
        public Nullable<System.DateTime> TimeCleared { get => _TimeCleared; set { _TimeCleared = value; OnPropertyChanged(); } }

    }
}
