//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis_SCADA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessData
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<double> Furnace_Temp { get; set; }
        public Nullable<double> PCondense_Flow { get; set; }
        public Nullable<double> PCondense_Press { get; set; }
        public Nullable<double> HLPHeater_Temp { get; set; }
        public Nullable<double> HLPHeater_Press { get; set; }
        public Nullable<double> HDeaerator_Temp { get; set; }
        public Nullable<double> HDeaerator_Press { get; set; }
        public Nullable<double> PSupply_Flow { get; set; }
        public Nullable<double> PSupply_Press { get; set; }
        public Nullable<double> HHPHeater_Temp { get; set; }
        public Nullable<double> HHPHeater_Press { get; set; }
        public Nullable<double> HBoiler_Temp { get; set; }
        public Nullable<double> HBoiler_Press { get; set; }
        public Nullable<double> TurbineH_Temp { get; set; }
        public Nullable<double> TurbineH_Press { get; set; }
        public Nullable<double> TurbineI_Temp { get; set; }
        public Nullable<double> TurbineI_Press { get; set; }
        public Nullable<double> TurbineL_Temp { get; set; }
        public Nullable<double> TurbineL_Press { get; set; }
        public Nullable<double> Turbine_Freq { get; set; }
        public Nullable<double> HCondenser_Temp { get; set; }
        public Nullable<double> PCircular_Flow { get; set; }
    }
}
