//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thesis_SCADA.Model
{
    using System;
    using System.Collections.Generic;
    using Thesis_SCADA.ViewModel;

    public partial class Users : BaseViewModel
    {
        public int Id { get; set; }

        private string _UserName;
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }

        private string _Password;
        public string Password { get => _Password; set { _Password = value; OnPropertyChanged(); } }

        private int _IdRole;
        public int IdRole { get => _IdRole; set { _IdRole = value; OnPropertyChanged(); } }

        private UserRole _UserRole { get; set; }
        public virtual UserRole UserRole { get => _UserRole; set { _UserRole = value; OnPropertyChanged(); } }

    }
}

